<?php
/**
 * One-Time Data Import: Rum Distilleries → WordPress
 *
 * Usage (WP-CLI):
 *   wp eval-file wp-content/themes/powerful-scotch/inc/import-rum.php
 *
 * @package PowerfulSpirits
 */

defined('ABSPATH') || exit;

/**
 * Main rum import function
 */
function ps_run_rum_import() {
    // Ensure taxonomies & CPT are registered
    if (!post_type_exists('distillery')) {
        ps_register_distillery_cpt();
    }
    if (!taxonomy_exists('spirit_type')) {
        ps_register_taxonomies();
    }

    // Create default terms including rum regions
    ps_create_default_terms();

    $distilleries = ps_get_rum_distillery_data();
    $imported = 0;
    $skipped  = 0;

    foreach ($distilleries as $d) {
        // Check if already exists by title
        $existing = get_posts([
            'post_type'      => 'distillery',
            'title'          => $d['name'],
            'posts_per_page' => 1,
            'post_status'    => 'any',
        ]);
        if (!empty($existing)) {
            $skipped++;
            if (defined('WP_CLI')) {
                WP_CLI::log("Skipped (exists): {$d['name']}");
            }
            continue;
        }

        // Create post with production process as body content
        $post_id = wp_insert_post([
            'post_title'   => $d['name'],
            'post_content' => $d['production_process'],
            'post_type'    => 'distillery',
            'post_status'  => 'publish',
            'post_name'    => sanitize_title($d['name']),
        ]);

        if (is_wp_error($post_id)) {
            if (defined('WP_CLI')) {
                WP_CLI::warning('Failed to create: ' . $d['name']);
            }
            continue;
        }

        // Set meta fields
        update_post_meta($post_id, 'latitude', $d['lat']);
        update_post_meta($post_id, 'longitude', $d['lng']);
        update_post_meta($post_id, 'distillery_status', 'Operating');
        update_post_meta($post_id, 'official_website', $d['website']);
        update_post_meta($post_id, 'water_source', $d['water_source']);
        update_post_meta($post_id, 'still_count', $d['stills']);
        update_post_meta($post_id, 'still_types', $d['still_types']);
        update_post_meta($post_id, 'expressions', $d['expressions']);
        update_post_meta($post_id, 'barrel_sources', $d['barrel_sources']);
        update_post_meta($post_id, 'raw_material', $d['raw_material']);
        update_post_meta($post_id, 'country', $d['country']);

        // Set spirit type taxonomy
        wp_set_object_terms($post_id, 'Rum', 'spirit_type');

        // Set region taxonomy
        if (!empty($d['region'])) {
            wp_set_object_terms($post_id, $d['region'], 'region');
        }

        $imported++;

        if (defined('WP_CLI')) {
            WP_CLI::log("Imported: {$d['name']} ({$d['country']}, {$d['lat']}, {$d['lng']})");
        }
    }

    // Flush transients
    delete_transient('ps_distilleries_rum');
    delete_transient('ps_distilleries_all');

    if (defined('WP_CLI')) {
        WP_CLI::log("Done. Imported: $imported, Skipped: $skipped");
    }

    return ['imported' => $imported, 'skipped' => $skipped];
}

// Auto-run when eval-file'd via WP-CLI
if (defined('WP_CLI') && WP_CLI) {
    ps_run_rum_import();
}

/**
 * Complete dataset: 173 Rum distilleries with GPS coordinates
 *
 * Data sourced from Rum Distilleries.xlsx
 * GPS coordinates converted from DMS to decimal format.
 */
function ps_get_rum_distillery_data() {
    return [
        ['name' => 'Antigua Distillery Ltd', 'country' => 'Antigua and Barbuda', 'region' => 'Caribbean', 'lat' => 17.1167, 'lng' => -61.8333, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'English Harbour 5 Year, Cavalier', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'https://www.antiguadistillery.com/'],
        ['name' => 'John Watling\'s Distillery', 'country' => 'Bahamas', 'region' => 'Caribbean', 'lat' => 25.075, 'lng' => -77.349, 'stills' => 'Multiple', 'still_types' => 'Pot and column stills', 'expressions' => 'John Watling\'s Pale, Amber, Buena Vista', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot and column distilled, aged in oak.', 'website' => 'https://johnwatlings.com/'],
        ['name' => 'Foursquare Rum Distillery', 'country' => 'Barbados', 'region' => 'Caribbean', 'lat' => 13.1292, 'lng' => -59.4756, 'stills' => '2', 'still_types' => 'Double retort copper pot still, twin column Coffey still', 'expressions' => 'Foursquare Premise, Dominus, Sovereignty, Doorly\'s', 'water_source' => 'Local', 'barrel_sources' => 'Ex-bourbon', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented 48-72 hours, pot and column distillation, blended and aged in ex-bourbon barrels.', 'website' => 'https://foursquarerumdistillery.com/'],
        ['name' => 'Mount Gay Distillery', 'country' => 'Barbados', 'region' => 'Caribbean', 'lat' => 13.1513, 'lng' => -59.6211, 'stills' => 'Multiple', 'still_types' => 'Pot and column stills, including Coffey still', 'expressions' => 'Mount Gay Eclipse, Black Barrel, XO, 1703', 'water_source' => 'Local well', 'barrel_sources' => 'Ex-bourbon, sherry, port', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented with proprietary yeast, double distillation in pot and column stills, aged in charred oak barrels in tropical climate.', 'website' => 'https://www.mountgayrum.com/'],
        ['name' => 'St. Nicholas Abbey', 'country' => 'Barbados', 'region' => 'Caribbean', 'lat' => 13.2714, 'lng' => -59.5878, 'stills' => '1', 'still_types' => 'Hybrid pot/column still', 'expressions' => 'St Nicholas Abbey 5,8,10,12,18, White Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane syrup', 'production_process' => 'Cane syrup fermented, distilled in hybrid still, aged in oak barrels.', 'website' => 'https://www.stnicholasabbey.com/'],
        ['name' => 'West Indies Rum Distillery', 'country' => 'Barbados', 'region' => 'Caribbean', 'lat' => 13.1381, 'lng' => -59.6306, 'stills' => '6', 'still_types' => '2 column, 4 pot stills including Vulcan triple chamber, Rockley', 'expressions' => 'Cockspur, Plantation rums (part)', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, distilled in pot and column stills including unique Vulcan chamber still, aged in oak.', 'website' => 'https://maisonferrand.com/en/home/stades-west-indies-rum-distillery'],
        ['name' => 'Copal Tree Distillery', 'country' => 'Belize', 'region' => 'Central America', 'lat' => 16.1, 'lng' => -88.8, 'stills' => 'Multiple', 'still_types' => 'Pot and column stills', 'expressions' => 'Copalli Rum varieties', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Organic cane juice fermented, pot and column distilled, aged in oak; sustainable practices.', 'website' => 'https://www.copaltreelodge.com/belize-rum-distillery'],
        ['name' => 'Cuello\'s Distillery', 'country' => 'Belize', 'region' => 'Central America', 'lat' => 18.0833, 'lng' => -88.5667, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Cuello\'s rums, various blends', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'https://www.cuellosdistilleryltd.bz/'],
        ['name' => 'Travellers Liquors', 'country' => 'Belize', 'region' => 'Central America', 'lat' => 17.25, 'lng' => -88.7667, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'One Barrel, Travellers Aged, 1-5 Barrel', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in ex-bourbon barrels.', 'website' => 'https://www.travellersliquorslimited.com/'],
        ['name' => 'Callwood Rum Distillery', 'country' => 'British Virgin Islands', 'region' => 'Caribbean', 'lat' => 18.4286, 'lng' => -64.6625, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Arundel Cane Rum White, Gold', 'water_source' => 'Local', 'barrel_sources' => 'Not aged', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented naturally, pot distilled, unaged or lightly aged.', 'website' => 'https://callwoodcanerum.com/'],
        ['name' => 'Cayman Spirits Co. (Seven Fathoms)', 'country' => 'Cayman Islands', 'region' => 'Caribbean', 'lat' => 19.3, 'lng' => -81.3833, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Seven Fathoms Premium, Governor\'s Reserve', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged underwater at 42 feet.', 'website' => 'https://caymanspirits.com/'],
        ['name' => 'Fábrica Nacional de Licores (Ron Centenario)', 'country' => 'Costa Rica', 'region' => 'Central America', 'lat' => 9.8667, 'lng' => -83.9167, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Centenario 12, 20, 25', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'https://www.centenario.cr/'],
        ['name' => 'Havana Club (Ronera San José/Santa Cruz)', 'country' => 'Cuba', 'region' => 'Caribbean', 'lat' => 23.15, 'lng' => -81.9167, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Havana Club 3 Años, 7 Años, Selección de Maestros', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled to aguardiente, blended and aged in oak.', 'website' => 'https://havana-club.com/'],
        ['name' => 'Ron Santiago de Cuba', 'country' => 'Cuba', 'region' => 'Caribbean', 'lat' => 20.0167, 'lng' => -75.8167, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Santiago de Cuba Añejo, Extra Añejo', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'https://www.ronsantiagodecuba.com/'],
        ['name' => 'Belfast Estate (Dominica Distillers)', 'country' => 'Dominica', 'region' => 'Caribbean', 'lat' => 15.5, 'lng' => -61.3667, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Belfast Special, D-Special, Bois Bande, Soca', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses or cane juice fermented, column distilled, spiced/infused variants aged in oak.', 'website' => 'http://belfastrums.com/'],
        ['name' => 'Macoucherie Rum (Shillingford Estate)', 'country' => 'Dominica', 'region' => 'Caribbean', 'lat' => 15.4167, 'lng' => -61.3333, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Macoucherie Dark, White', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'https://macoucherierum.com/'],
        ['name' => 'Barceló', 'country' => 'Dominican Republic', 'region' => 'Caribbean', 'lat' => 18.45, 'lng' => -69.3, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Barceló Imperial, Gran Añejo', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'https://www.ronbarcelo.com/'],
        ['name' => 'Bermúdez', 'country' => 'Dominican Republic', 'region' => 'Caribbean', 'lat' => 19.45, 'lng' => -70.7, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Bermúdez Añejo, Reserva', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'https://www.bermudez.com/'],
        ['name' => 'Brugal', 'country' => 'Dominican Republic', 'region' => 'Caribbean', 'lat' => 19.8, 'lng' => -70.6833, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Brugal Añejo, Extra Viejo, 1888', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'https://www.brugal-rum.com/'],
        ['name' => 'Ron Cihuatán', 'country' => 'El Salvador', 'region' => 'Central America', 'lat' => 13.7, 'lng' => -89.2, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Cihuatán 12, Solera 25', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, solera aged in oak.', 'website' => 'https://roncihuatan.com/'],
        ['name' => 'Clarke’s Court (Grenada Distillers Ltd)', 'country' => 'Grenada', 'region' => 'Caribbean', 'lat' => 12.0167, 'lng' => -61.7333, 'stills' => 'Multiple', 'still_types' => 'Pot and column', 'expressions' => 'Clarke\'s Court Pure White, Old Grog', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot and column distilled, aged in oak.', 'website' => 'https://www.grenadadistillers.com/'],
        ['name' => 'River Antoine Estate Rum Distillery', 'country' => 'Grenada', 'region' => 'Caribbean', 'lat' => 12.2167, 'lng' => -61.6333, 'stills' => '1', 'still_types' => 'Water wheel-propelled pot still', 'expressions' => 'Rivers Royale, overproof', 'water_source' => 'Local river', 'barrel_sources' => 'Not aged (mostly)', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented naturally, pot distilled in wood-fired still, unaged overproof.', 'website' => 'Not specified'],
        ['name' => 'Westerhall Estate', 'country' => 'Grenada', 'region' => 'Caribbean', 'lat' => 12.0333, 'lng' => -61.6833, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Westerhall Vintage, Plantation', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak.', 'website' => 'https://westerhallrums.com/'],
        ['name' => 'Bielle', 'country' => 'Guadeloupe', 'region' => 'Caribbean', 'lat' => 15.8833, 'lng' => -61.2333, 'stills' => 'Multiple', 'still_types' => 'Creole column stills', 'expressions' => 'Bielle Blanc, Vieux, Brut de Fût', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, Creole column distilled, aged in oak.', 'website' => 'https://rhum-bielle.com/'],
        ['name' => 'Damoiseau', 'country' => 'Guadeloupe', 'region' => 'Caribbean', 'lat' => 16.3333, 'lng' => -61.3333, 'stills' => 'Multiple', 'still_types' => 'Creole column stills, some molasses', 'expressions' => 'Damoiseau Blanc, Vieux, XO', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice/molasses mix', 'production_process' => 'Cane juice/molasses fermented, Creole column distilled, aged in oak.', 'website' => 'https://rhum-damoiseau.com/'],
        ['name' => 'Longueteau (Espérance)', 'country' => 'Guadeloupe', 'region' => 'Caribbean', 'lat' => 16.05, 'lng' => -61.5667, 'stills' => 'Multiple', 'still_types' => 'Creole column stills', 'expressions' => 'Longueteau Blanc, Genesis, Parcellaire', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice from single parcels fermented, Creole column distilled, aged in oak.', 'website' => 'https://www.rhumlongueteau.fr/'],
        ['name' => 'Montebello', 'country' => 'Guadeloupe', 'region' => 'Caribbean', 'lat' => 16.1833, 'lng' => -61.6167, 'stills' => 'Multiple', 'still_types' => 'Creole column stills', 'expressions' => 'Montebello Blanc, Vieux', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, Creole column distilled, aged in oak.', 'website' => 'https://www.montebello.fr/'],
        ['name' => 'Père Labat (Poisson)', 'country' => 'Guadeloupe', 'region' => 'Caribbean', 'lat' => 15.9667, 'lng' => -61.25, 'stills' => '1 (oldest in Caribbean)', 'still_types' => 'Creole column stills', 'expressions' => 'Père Labat Blanc, Réserve Spéciale', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, distilled in oldest Creole column, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'Reimonenq', 'country' => 'Guadeloupe', 'region' => 'Caribbean', 'lat' => 16.3333, 'lng' => -61.7, 'stills' => 'Multiple', 'still_types' => 'Creole column stills', 'expressions' => 'Reimonenq Blanc, Vieux', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, Creole column distilled, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'Severin', 'country' => 'Guadeloupe', 'region' => 'Caribbean', 'lat' => 16.3333, 'lng' => -61.7, 'stills' => 'Multiple', 'still_types' => 'Creole column stills', 'expressions' => 'Severin Blanc, Vieux', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, Creole column distilled, aged in oak.', 'website' => 'https://www.rhum-severin.com/'],
        ['name' => 'Botran (Industrias Licoreras Quetzalteca)', 'country' => 'Guatemala', 'region' => 'Central America', 'lat' => 14.8333, 'lng' => -91.5167, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Botran Reserva, Solera 1893', 'water_source' => 'High altitude', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane honey/molasses', 'production_process' => 'Cane honey/molasses fermented, column distilled, solera aged in high-altitude warehouses.', 'website' => 'https://www.botran.com/'],
        ['name' => 'Industrias Licoreras de Guatemala (Ron Zacapa)', 'country' => 'Guatemala', 'region' => 'Central America', 'lat' => 14.8333, 'lng' => -91.5167, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Ron Zacapa Centenario 23, XO', 'water_source' => 'High altitude', 'barrel_sources' => 'Oak (various)"', 'raw_material' => 'Virgin sugar cane honey', 'production_process' => 'Virgin cane honey fermented with pineapple yeast, column distilled, solera aged at high altitude in various casks.', 'website' => 'https://www.zacaparum.com/'],
        ['name' => 'Diamond Distillery (Demerara Distillers Ltd)', 'country' => 'Guyana', 'region' => 'South America', 'lat' => 6.8135, 'lng' => -58.1167, 'stills' => '9+', 'still_types' => 'Wooden Coffey still (Enmore), Double Wooden Pot (Port Mourant), Single Wooden Pot (Versailles), French Savalle 4-column, English Coffey 2-column, etc.', 'expressions' => 'El Dorado 3,5,8,12,15,21,25; Single still like Port Mourant, Enmore', 'water_source' => 'Demerara River', 'barrel_sources' => 'Ex-bourbon oak barrels', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented for 3-5 days with proprietary yeasts, distilled in heritage wooden and metal stills to various marques (light to heavy), aged in ex-bourbon barrels with angel\'s share up to 7% annually.', 'website' => 'https://theeldoradorum.com/'],
        ['name' => 'Barbancourt Distillery', 'country' => 'Haiti', 'region' => 'Caribbean', 'lat' => 18.5333, 'lng' => -72.3333, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Barbancourt 3 Star, 5 Star, Reserve Speciale', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, column distilled twice like cognac, aged in oak.', 'website' => 'https://barbancourt.com/'],
        ['name' => 'Appleton Estate', 'country' => 'Jamaica', 'region' => 'Caribbean', 'lat' => 18.0744, 'lng' => -77.7406, 'stills' => '4 pot stills', 'still_types' => 'Pot and column', 'expressions' => 'Appleton Signature, Reserve, Rare Blend 12, 21', 'water_source' => 'Local spring', 'barrel_sources' => 'Ex-bourbon', 'raw_material' => 'Molasses', 'production_process' => 'Molasses with dunder fermented 5-30 days for high esters, pot and column distilled, aged in ex-bourbon barrels.', 'website' => 'https://www.appletonestate.com/'],
        ['name' => 'Clarendon Distillery (Monymusk)', 'country' => 'Jamaica', 'region' => 'Caribbean', 'lat' => 17.8, 'lng' => -77.2833, 'stills' => 'Multiple', 'still_types' => 'Pot and column (industrial scale)', 'expressions' => 'Monymusk, bulk blends', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented with dunder, pot and column distilled at scale, mostly for bulk.', 'website' => 'Not specified'],
        ['name' => 'Hampden Estate', 'country' => 'Jamaica', 'region' => 'Caribbean', 'lat' => 18.4992, 'lng' => -77.6875, 'stills' => 'Multiple', 'still_types' => 'Pot stills (high-ester focus)', 'expressions' => 'Hampden Estate, Rum Fire, high-ester marques', 'water_source' => 'Local', 'barrel_sources' => 'Ex-bourbon', 'raw_material' => 'Molasses', 'production_process' => 'Molasses with dunder and muck pits fermented 1-3 weeks, pot distilled to high ester levels, aged or unaged.', 'website' => 'https://hampdenestaterum.com/'],
        ['name' => 'Long Pond Distillery', 'country' => 'Jamaica', 'region' => 'Caribbean', 'lat' => 18.5, 'lng' => -77.6667, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Long Pond marques, Captain Morgan (part)', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses with dunder fermented long, pot distilled to various marques, aged or blended.', 'website' => 'Not specified'],
        ['name' => 'Worthy Park Estate', 'country' => 'Jamaica', 'region' => 'Caribbean', 'lat' => 18.1428, 'lng' => -77.1531, 'stills' => 'Multiple', 'still_types' => 'Pot and column stills', 'expressions' => 'Worthy Park Single Estate, Rum-Bar', 'water_source' => 'Local', 'barrel_sources' => 'Ex-bourbon', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented 2-3 weeks with wild yeast, pot and column distilled, aged in ex-bourbon.', 'website' => 'https://worthyparkestate.com/'],
        ['name' => 'Depaz', 'country' => 'Martinique', 'region' => 'Caribbean', 'lat' => 14.75, 'lng' => -61.1667, 'stills' => 'Multiple', 'still_types' => 'Creole column stills', 'expressions' => 'Depaz Blanc, Vieux, XO', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, Creole column distilled, aged in oak.', 'website' => 'https://depaz.fr/'],
        ['name' => 'Habitation Saint-Étienne (HSE)', 'country' => 'Martinique', 'region' => 'Caribbean', 'lat' => 14.7, 'lng' => -61.0, 'stills' => 'Multiple', 'still_types' => 'Creole column stills', 'expressions' => 'HSE Blanc, Vieux, Parcellaire', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, Creole column distilled, aged in various oak.', 'website' => 'https://www.rhumhse.com/'],
        ['name' => 'La Favorite', 'country' => 'Martinique', 'region' => 'Caribbean', 'lat' => 14.6167, 'lng' => -61.0333, 'stills' => 'Multiple', 'still_types' => 'Creole column stills', 'expressions' => 'La Favorite Blanc, Ambré, Vieux', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented 72 hours, Creole column distilled, aged in oak.', 'website' => 'https://www.rhum-lafavorite.com/'],
        ['name' => 'Neisson', 'country' => 'Martinique', 'region' => 'Caribbean', 'lat' => 14.7167, 'lng' => -61.1833, 'stills' => 'Multiple', 'still_types' => 'Creole column stills', 'expressions' => 'Neisson Blanc, Profil, Vieux', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, Creole column distilled to low proof, aged in oak.', 'website' => 'https://rhumneisson.com/'],
        ['name' => 'Rhum Clément (Simon)', 'country' => 'Martinique', 'region' => 'Caribbean', 'lat' => 14.6167, 'lng' => -60.9167, 'stills' => 'Multiple', 'still_types' => 'Creole column stills', 'expressions' => 'Clément Blanc, Vieux, Canne Bleue', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, Creole column distilled, aged in oak.', 'website' => 'https://rhumclementusa.com/'],
        ['name' => 'Rhum J.M (Fonds Préville)', 'country' => 'Martinique', 'region' => 'Caribbean', 'lat' => 14.8833, 'lng' => -61.1333, 'stills' => 'Multiple', 'still_types' => 'Creole column stills', 'expressions' => 'Rhum J.M Blanc, Vieux, XO', 'water_source' => 'Local', 'barrel_sources' => 'Oak (French, American)', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented 48-72 hours, single distillation in Creole column, aged in oak.', 'website' => 'https://rhum-jm.com/'],
        ['name' => 'Saint James', 'country' => 'Martinique', 'region' => 'Caribbean', 'lat' => 14.7833, 'lng' => -60.9833, 'stills' => 'Multiple', 'still_types' => 'Creole column stills', 'expressions' => 'Saint James Blanc, Impérial, Royal Ambré', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, Creole column distilled, aged in oak.', 'website' => 'https://rhum-saintjames.com/'],
        ['name' => 'Compañía Licorera de Nicaragua (Flor de Caña)', 'country' => 'Nicaragua', 'region' => 'Central America', 'lat' => 12.6333, 'lng' => -86.9833, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Flor de Caña 12, 18, 25', 'water_source' => 'Volcanic area', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak at volcanic base; eco-friendly.', 'website' => 'https://www.flordecana.com/'],
        ['name' => 'Hacienda San Isidro (Varela Hermanos)', 'country' => 'Panama', 'region' => 'Central America', 'lat' => 7.9333, 'lng' => -80.6167, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Various Abuelo expressions', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in ex-bourbon and other oak.', 'website' => 'https://www.ronabuelo.com/'],
        ['name' => 'Varela Hermanos (Ron Abuelo)', 'country' => 'Panama', 'region' => 'Central America', 'lat' => 7.9333, 'lng' => -80.6167, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Ron Abuelo Añejo, 7 Años, Centuria', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak; family-owned since 1908.', 'website' => 'https://www.ronabuelo.com/'],
        ['name' => 'Bacardi', 'country' => 'Puerto Rico', 'region' => 'Caribbean', 'lat' => 18.4411, 'lng' => -66.14, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Bacardi Superior, Gold, 8, Reserva Ocho', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, multi-column distilled, charcoal filtered, aged in oak.', 'website' => 'https://www.bacardi.com/'],
        ['name' => 'Destilería Serrallés (Don Q)', 'country' => 'Puerto Rico', 'region' => 'Caribbean', 'lat' => 18.0, 'lng' => -66.6167, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Don Q Cristal, Gold, Añejo', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, multi-column distilled, aged in oak.', 'website' => 'https://donq.com/'],
        ['name' => 'Ron del Barrilito (Edmundo B. Fernández)', 'country' => 'Puerto Rico', 'region' => 'Caribbean', 'lat' => 18.4, 'lng' => -66.15, 'stills' => 'Multiple', 'still_types' => 'Pot and column', 'expressions' => 'Ron del Barrilito 2 Stars, 3 Stars', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot and column distilled, aged in sherry casks.', 'website' => 'https://rondelbarrilito.com/'],
        ['name' => 'St. Lucia Distillers', 'country' => 'St. Lucia', 'region' => 'Caribbean', 'lat' => 13.9667, 'lng' => -61.0333, 'stills' => 'Multiple', 'still_types' => 'Pot and column', 'expressions' => 'Chairman\'s Reserve, Admiral Rodney, Bounty', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses/cane juice', 'production_process' => 'Molasses or cane juice fermented, pot and column distilled, blended and aged in oak.', 'website' => 'https://www.stluciadistillers.com/'],
        ['name' => 'St. Vincent Distillers (Sunset Rum)', 'country' => 'St. Vincent and the Grenadines', 'region' => 'Caribbean', 'lat' => 13.2833, 'lng' => -61.1333, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Sunset Very Strong, Captain Bligh XO', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'Angostura Distillery', 'country' => 'Trinidad and Tobago', 'region' => 'Caribbean', 'lat' => 10.65, 'lng' => -61.4833, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Angostura 1824, 1919, Royal Oak', 'water_source' => 'Local', 'barrel_sources' => 'Ex-bourbon', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented with proprietary yeast, column distilled to various strengths, aged in ex-bourbon.', 'website' => 'https://angostura.com/'],
        ['name' => 'Cruzan Distillery', 'country' => 'US Virgin Islands', 'region' => 'Caribbean', 'lat' => 17.7028, 'lng' => -64.8722, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Cruzan Aged Light, Dark, Single Barrel', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, five-column distilled, aged in oak.', 'website' => 'https://www.cruzanrum.com/'],
        ['name' => 'Privateer Rum', 'country' => 'United States', 'region' => 'North America', 'lat' => 42.679, 'lng' => -70.835, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Privateer True American Amber, White, Navy Yard', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in new American oak and ex-bourbon barrels; emphasis on transparency and no additives.', 'website' => 'https://privateerrum.com/'],
        ['name' => 'Montanya Distillers', 'country' => 'United States', 'region' => 'North America', 'lat' => 38.8697, 'lng' => -106.9878, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Montanya Platino, Oro, Exclusiva', 'water_source' => 'Mountain spring', 'barrel_sources' => 'Oak (American/French)', 'raw_material' => 'Cane juice/molasses', 'production_process' => 'Organic cane fermented, pot distilled at high altitude, aged in American oak, French oak, and ex-spirit barrels.', 'website' => 'https://www.montanyarum.com/'],
        ['name' => 'Roulaison Distilling', 'country' => 'United States', 'region' => 'North America', 'lat' => 29.9511, 'lng' => -90.0715, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Roulaison White, Amber, Spiced', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Louisiana sugarcane molasses fermented, column distilled, aged in oak; inspired by local culture.', 'website' => 'https://www.roulaison.com/'],
        ['name' => 'Bayou Rum', 'country' => 'United States', 'region' => 'North America', 'lat' => 30.3, 'lng' => -92.9167, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Bayou Silver, Spiced, Satsuma', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, flavored variants aged in oak.', 'website' => 'https://bayourum.com/'],
        ['name' => 'Kō Hana Distillers', 'country' => 'United States', 'region' => 'North America', 'lat' => 21.4, 'lng' => -158.0333, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Kō Hana Kea, Koa, Agricole', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Fresh Hawaiian sugarcane juice fermented, column distilled, aged in oak; agricole-style.', 'website' => 'https://kohana.com/'],
        ['name' => 'Lyon Rum (Windsor Distilling)', 'country' => 'United States', 'region' => 'North America', 'lat' => 39.6243, 'lng' => -77.4108, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Lyon Rum Reserve, Dark', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak; award-winning craft.', 'website' => 'Not specified'],
        ['name' => 'Muddy River Distillery', 'country' => 'United States', 'region' => 'North America', 'lat' => 35.2, 'lng' => -81.0333, 'stills' => 'Multiple', 'still_types' => 'Custom stills', 'expressions' => 'Muddy River Silver, Spiced', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, distilled, aged in oak; premium ingredients.', 'website' => 'https://muddyriverdistillery.com/'],
        ['name' => 'Paranubes', 'country' => 'Mexico', 'region' => 'Central America', 'lat' => 17.0, 'lng' => -96.5, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Paranubes Oaxaca', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Fresh cane juice fermented naturally, column distilled to high proof; funky, agricole-like.', 'website' => 'https://www.paranubes.com/'],
        ['name' => 'El Ron Prohibido', 'country' => 'Mexico', 'region' => 'Central America', 'lat' => 19.0, 'lng' => -96.9167, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'El Ron Prohibido Habanero Solera 12, Gran Reserva 15', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, solera aged; habanero-infused variants.', 'website' => 'https://ronprohibido.com/'],
        ['name' => 'Ron Mocambo (Licores Veracruz)', 'country' => 'Mexico', 'region' => 'Central America', 'lat' => 19.1736, 'lng' => -96.1342, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Mocambo 20 Years Edición de Arte', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, long-aged in oak; artisanal Veracruz style.', 'website' => 'http://www.licoresveracruz.com/'],
        ['name' => 'Charanda Uruapan (various, e.g. Sol Tarasco)', 'country' => 'Mexico', 'region' => 'Central America', 'lat' => 19.4167, 'lng' => -102.05, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Charanda Sol Tarasco, El Tarasco', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, column distilled; Denomination of Origin protected charanda style.', 'website' => 'Not specified'],
        ['name' => 'Dakabend', 'country' => 'Mexico', 'region' => 'Central America', 'lat' => 17.0, 'lng' => -96.5, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Dakabend Blanco, Añejo', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Artisanal cane juice fermented, distilled; modern Mexican caña style.', 'website' => 'https://www.dakabend.com/'],
        ['name' => 'Santa Teresa', 'country' => 'Venezuela', 'region' => 'South America', 'lat' => 10.25, 'lng' => -67.6167, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Santa Teresa 1796, Linaje', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, solera aged in oak; Venezuelan DO standards.', 'website' => 'https://www.santateresarum.com/'],
        ['name' => 'Diplomatico (Destilerías Unidas)', 'country' => 'Venezuela', 'region' => 'South America', 'lat' => 9.5, 'lng' => -70.8333, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Diplomatico Reserva Exclusiva, Distillation Collection', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in various oak; solera and batch aging.', 'website' => 'https://www.diplomatico.com/'],
        ['name' => 'Dictador', 'country' => 'Colombia', 'region' => 'South America', 'lat' => 10.3997, 'lng' => -75.504, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Dictador 12, XO Perpetual', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak; premium Colombian style.', 'website' => 'https://dictador.com/'],
        ['name' => 'Ron Cartagena (various)', 'country' => 'Colombia', 'region' => 'South America', 'lat' => 10.3997, 'lng' => -75.504, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Various Colombian rums', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'Cartavio', 'country' => 'Peru', 'region' => 'South America', 'lat' => -7.8667, 'lng' => -79.0167, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Cartavio Ron Añejo, XO', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak; high-altitude influence possible.', 'website' => 'https://roncartavio.com/'],
        ['name' => 'Ron Millonario', 'country' => 'Peru', 'region' => 'South America', 'lat' => 0.0, 'lng' => 0.0, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Ron Millonario 15, XO Cask', 'water_source' => 'Local high altitude', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged at altitude in oak for slower maturation.', 'website' => 'Not specified'],
        ['name' => 'Zhumir', 'country' => 'Ecuador', 'region' => 'South America', 'lat' => 0.0, 'lng' => 0.0, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Zhumir Aguardiente, Ron variants', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane honey/juice', 'production_process' => 'Cane honey fermented, distilled, aged; high-altitude Ecuador style.', 'website' => 'Not specified'],
        ['name' => 'Wicked Dolphin Distillery', 'country' => 'United States', 'region' => 'North America', 'lat' => 26.5667, 'lng' => -81.9761, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Crystal Rum, Coconut Rum, Black Rum, Spiced Rum, Vanilla Rum, Florida Cane Rum', 'water_source' => 'Local Florida', 'barrel_sources' => 'Oak (charred American)', 'raw_material' => 'Florida sugarcane/molasses', 'production_process' => 'Florida sugarcane/molasses fermented, column distilled in small batches, aged in charred American oak; focus on local ingredients and award-winning quality.', 'website' => 'https://wickeddolphin.com/'],
        ['name' => 'Key West First Legal Rum Distillery', 'country' => 'United States', 'region' => 'North America', 'lat' => 24.5592, 'lng' => -81.8025, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Chef Distilled White Rum, Spiced Rum, Vanilla Brûlée Rum, Salted Caramel Rum', 'water_source' => 'Local', 'barrel_sources' => 'New American oak', 'raw_material' => 'Sugarcane molasses', 'production_process' => 'Molasses fermented, pot distilled, some salt-cured in seawater, aged in new American oak barrels; artisanal process with chef-inspired flavors.', 'website' => 'https://www.keywestlegalrum.com/'],
        ['name' => 'Papa\'s Pilar Rum Distillery', 'country' => 'United States', 'region' => 'North America', 'lat' => 24.5583, 'lng' => -81.8028, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Blonde Rum, Dark Rum, Sherry Finished, Rye Finished', 'water_source' => 'Local', 'barrel_sources' => 'Oak (various finishes)', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, blended from multiple sources, aged in oak with solera method and various finishes like sherry or rye barrels.', 'website' => 'https://papaspilar.com/'],
        ['name' => 'Islamorada Brewery & Distillery', 'country' => 'United States', 'region' => 'North America', 'lat' => 24.9236, 'lng' => -80.6325, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Islamorada Rum, Spiced Rum, Coconut Rum, Key Lime Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, infused with local flavors like key lime or coconut, aged in oak.', 'website' => 'https://www.islamoradabreweryanddistillery.com/'],
        ['name' => 'Big Cypress Distillery', 'country' => 'United States', 'region' => 'North America', 'lat' => 25.61, 'lng' => -80.43, 'stills' => 'Multiple', 'still_types' => 'Pot and column stills', 'expressions' => 'Hell’s Bay Rum, Orange Spiced Rum', 'water_source' => 'Local', 'barrel_sources' => 'New American oak', 'raw_material' => 'Organic sugar and molasses', 'production_process' => 'Organic sugar/molasses fermented, pot and column distilled, aged in charred new American oak; infusions like orange peels, citrus, vanilla for spiced variants.', 'website' => 'https://bigcypressdistillery.com/'],
        ['name' => 'Siesta Key Rum (Drum Circle Distilling)', 'country' => 'United States', 'region' => 'North America', 'lat' => 27.3556, 'lng' => -82.5142, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Siesta Key Toasted Coconut Rum, Spiced Rum, Silver Rum, Gold Rum', 'water_source' => 'Local', 'barrel_sources' => 'Ex-bourbon oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented with proprietary yeast, pot distilled in small batches, aged in ex-bourbon oak; hand-toasted coconut infusions for signature expression.', 'website' => 'https://siestakeyrum.com/'],
        ['name' => 'Novo Fogo Cachaça Distillery', 'country' => 'Brazil', 'region' => 'South America', 'lat' => -25.4833, 'lng' => -48.8333, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Silver Cachaça, Barrel-Aged Cachaça, Sparkling Caipirinha', 'water_source' => 'Local spring', 'barrel_sources' => 'Brazilian woods (various)', 'raw_material' => 'Sugarcane juice', 'production_process' => 'Organic sugarcane juice fermented naturally, pot distilled in zero-waste facility, aged in Brazilian woods like amburana or oak; USDA certified organic.', 'website' => 'https://novofogo.com/'],
        ['name' => 'Maison Leblon Cachaça Distillery', 'country' => 'Brazil', 'region' => 'South America', 'lat' => -18.5833, 'lng' => -46.5167, 'stills' => 'Multiple', 'still_types' => 'Column stills (alambique)', 'expressions' => 'Leblon Reserva Especial, Natural Cane', 'water_source' => 'Local', 'barrel_sources' => 'French oak', 'raw_material' => 'Sugarcane juice', 'production_process' => 'Fresh sugarcane juice pressed within hours, fermented, distilled in alambique stills, aged in French oak; artisanal process with French influence.', 'website' => 'https://www.leblon.com/'],
        ['name' => 'Soul Premium Cachaça Distillery', 'country' => 'Brazil', 'region' => 'South America', 'lat' => -20.0, 'lng' => -45.0, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Soul Premium Cachaça, Aged variants', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Sugarcane juice', 'production_process' => 'Finest natural sugarcane fermented meticulously, pot distilled with exacting methods, aged in oak; focus on premium quality and awards.', 'website' => 'https://soulcachaca.com/'],
        ['name' => 'Yaguara Cachaça Distillery', 'country' => 'Brazil', 'region' => 'South America', 'lat' => -20.0, 'lng' => -45.0, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Yaguara Branca, Ouro, Blended', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Sugarcane juice', 'production_process' => 'Organic sugarcane juice fermented, pot distilled artisanally on family farm, aged in oak; emphasis on retention and international appeal.', 'website' => 'https://yaguara.com/'],
        ['name' => 'Cachaça Magnífica Distillery', 'country' => 'Brazil', 'region' => 'South America', 'lat' => -22.4, 'lng' => -43.6667, 'stills' => 'Multiple', 'still_types' => 'Pot stills (alambique)', 'expressions' => 'Magnífica Tradicional, Reserva Soleira, Envelhecida', 'water_source' => 'Local', 'barrel_sources' => 'Oak (various)', 'raw_material' => 'Sugarcane juice', 'production_process' => 'Sugarcane juice fermented, pot distilled in small alambique, solera aged in oak; artisanal quality focus for pot still category.', 'website' => 'https://cachacamagnifica.com/'],
        ['name' => 'Abelha Cachaça Distillery', 'country' => 'Brazil', 'region' => 'South America', 'lat' => -14.0, 'lng' => -40.0, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Abelha Silver, Gold', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Sugarcane juice', 'production_process' => 'Organic sugarcane juice fermented naturally, pot distilled artisanally, aged in oak; emphasis on sustainable small-farm production.', 'website' => 'https://www.abelha.com/'],
        ['name' => 'DropWorks Rum Distillery', 'country' => 'United Kingdom', 'region' => 'Europe', 'lat' => 53.2667, 'lng' => -1.0333, 'stills' => 'Multiple', 'still_types' => 'Pot and column stills', 'expressions' => 'Clear Drop, Fun Rum, Funk Drop', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented with proprietary yeast, pot and column distilled, aged in various oak; modern British style.', 'website' => 'https://dropworks.co.uk/'],
        ['name' => 'Spirited Union Rum Co.', 'country' => 'Netherlands', 'region' => 'Europe', 'lat' => 52.3667, 'lng' => 4.9, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Sweet Dram, Pink Grapefruit, Pineapple', 'water_source' => 'Local', 'barrel_sources' => 'Various botanicals infused', 'raw_material' => 'Molasses/cane juice', 'production_process' => 'Molasses or cane juice fermented, pot distilled, infused with botanicals, aged in barrels.', 'website' => 'https://spirited-union.com/'],
        ['name' => 'Mounts Bay Distillery', 'country' => 'United Kingdom', 'region' => 'Europe', 'lat' => 50.1167, 'lng' => -5.5333, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Penzance Rum, Spiced Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak; Cornish style.', 'website' => 'https://mountsbaydistillery.com/'],
        ['name' => 'North Point Distillery', 'country' => 'United Kingdom', 'region' => 'Europe', 'lat' => 59.0, 'lng' => -3.0, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Pilot Rum, Spiced Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'J. Gow Rum', 'country' => 'United Kingdom', 'region' => 'Europe', 'lat' => 59.0, 'lng' => -3.0, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Revenge, Fading Light XO', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'Dark Matter Distillers', 'country' => 'United Kingdom', 'region' => 'Europe', 'lat' => 57.05, 'lng' => -2.5, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Dark Matter Spiced Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, spiced and aged.', 'website' => 'https://darkmatterdistillers.com/'],
        ['name' => 'Islay Rum Distillery', 'country' => 'United Kingdom', 'region' => 'Europe', 'lat' => 55.75, 'lng' => -6.25, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Islay Rum Peat Smoked', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled with peat influence, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'Glasgow Distillery Co', 'country' => 'United Kingdom', 'region' => 'Europe', 'lat' => 55.8667, 'lng' => -4.25, 'stills' => 'Multiple', 'still_types' => 'Pot and column', 'expressions' => 'Malt Riot Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, distilled, aged in oak.', 'website' => 'https://glasgowdistillery.com/'],
        ['name' => 'Revival Rum', 'country' => 'United Kingdom', 'region' => 'Europe', 'lat' => 52.25, 'lng' => -0.8833, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Revival Signature Blend', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented during lockdown, pot distilled, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'Three Counties Spirits Co.', 'country' => 'United Kingdom', 'region' => 'Europe', 'lat' => 0.0, 'lng' => 0.0, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Three Counties Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'Treguddick Distillery', 'country' => 'United Kingdom', 'region' => 'Europe', 'lat' => 50.4167, 'lng' => -4.95, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Treguddick Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'Two Drifters Distillery', 'country' => 'United Kingdom', 'region' => 'Europe', 'lat' => 50.7, 'lng' => -3.5333, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Two Drifters Overproof Spiced Pineapple Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled with pineapple, aged in oak.', 'website' => 'https://twodriftersrum.com/'],
        ['name' => 'Arehucas Rum Distillery', 'country' => 'Spain', 'region' => 'Europe', 'lat' => 28.1167, 'lng' => -15.5167, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Arehucas Carta Oro, Reserva Especial', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak; Canary style.', 'website' => 'https://arehucas.com/'],
        ['name' => 'Ron Aldea', 'country' => 'Spain', 'region' => 'Europe', 'lat' => 28.6667, 'lng' => -17.7667, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Ron Aldea Maestro, Familia', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot distilled, aged in oak.', 'website' => 'https://ronaldea.com/'],
        ['name' => 'Ron Montero', 'country' => 'Spain', 'region' => 'Europe', 'lat' => 36.7333, 'lng' => -3.5167, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Ron Montero Francisco Montero', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak; mainland Spain style.', 'website' => 'https://ronmontero.com/'],
        ['name' => 'Destilerías Belmonte', 'country' => 'Spain', 'region' => 'Europe', 'lat' => 37.9833, 'lng' => -1.1333, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Ron Belmonte Añejo', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'Bodegas Suau', 'country' => 'Spain', 'region' => 'Europe', 'lat' => 39.5667, 'lng' => 2.65, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Suau Brandy, Rum variants', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, distilled, aged in oak; historic family distillery.', 'website' => 'https://bodegassuau.com/'],
        ['name' => 'Engenhos do Norte', 'country' => 'Portugal', 'region' => 'Europe', 'lat' => 32.7667, 'lng' => -16.8333, 'stills' => 'Multiple', 'still_types' => 'Creole column stills', 'expressions' => 'Branca, 970 Reserva', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, Creole column distilled, aged in oak.', 'website' => 'https://engenhosdonorte.com/'],
        ['name' => 'William Hinton', 'country' => 'Portugal', 'region' => 'Europe', 'lat' => 32.7333, 'lng' => -17.1833, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'William Hinton Natural, Aged', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, column distilled, aged in various casks.', 'website' => 'https://williamhintonrum.com/'],
        ['name' => 'O Reizinho', 'country' => 'Portugal', 'region' => 'Europe', 'lat' => 32.7667, 'lng' => -16.8333, 'stills' => '1', 'still_types' => 'Pot still', 'expressions' => 'O Reizinho Aguardente', 'water_source' => 'Local', 'barrel_sources' => 'Not aged', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot distilled, unaged.', 'website' => 'Not specified'],
        ['name' => 'Engenhos da Calheta', 'country' => 'Portugal', 'region' => 'Europe', 'lat' => 32.7167, 'lng' => -17.1667, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Engenhos da Calheta Aguardente', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, column distilled, some aged.', 'website' => 'Not specified'],
        ['name' => 'Engenho Novo da Madeira', 'country' => 'Portugal', 'region' => 'Europe', 'lat' => 32.75, 'lng' => -17.0, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'William Hinton 6 Anos', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot distilled, aged in French oak.', 'website' => 'Not specified'],
        ['name' => 'Stroh Rum', 'country' => 'Austria', 'region' => 'Europe', 'lat' => 46.6167, 'lng' => 14.3, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Stroh 80, 60, 40', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, flavored; Inländer Rum style.', 'website' => 'https://stroh.at/'],
        ['name' => 'Brennerei & Weingut Wild', 'country' => 'Germany', 'region' => 'Europe', 'lat' => 48.0, 'lng' => 8.0, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Blackforest Wild Rum, Spiced Rum', 'water_source' => 'Local spring', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented spontaneously, double distilled, aged in various barrels.', 'website' => 'https://wild-brennerei.de/'],
        ['name' => 'Pott Rum', 'country' => 'Germany', 'region' => 'Europe', 'lat' => 54.7833, 'lng' => 9.4333, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Pott 54, Verschnitt', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, blended; traditional Flensburg style.', 'website' => 'https://pott-rum.de/'],
        ['name' => 'Schlitzer Destillerie', 'country' => 'Germany', 'region' => 'Europe', 'lat' => 50.6667, 'lng' => 9.5667, 'stills' => 'Multiple', 'still_types' => 'Pot and column', 'expressions' => 'Schlitzer Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, distilled, aged in oak.', 'website' => 'https://schlitzer-destillerie.de/'],
        ['name' => 'Lantenhammer (Rumult)', 'country' => 'Germany', 'region' => 'Europe', 'lat' => 47.75, 'lng' => 12.1333, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Rumult Bavarian Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented long, pot distilled, aged in oak; Bavarian style.', 'website' => 'https://lantenhammer.de/'],
        ['name' => 'Simon\'s Feinbrennerei', 'country' => 'Germany', 'region' => 'Europe', 'lat' => 48.0, 'lng' => 11.0, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Simon\'s Bavarian Pure Pot Still Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak.', 'website' => 'https://simons-feinbrennerei.de/'],
        ['name' => 'Stauning Whisky', 'country' => 'Denmark', 'region' => 'Europe', 'lat' => 55.9667, 'lng' => 8.3667, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Stauning Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak.', 'website' => 'https://stauningwhisky.dk/'],
        ['name' => 'Sams Island Distillery', 'country' => 'Denmark', 'region' => 'Europe', 'lat' => 55.8333, 'lng' => 10.6, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Sams Island Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'Braunstein', 'country' => 'Denmark', 'region' => 'Europe', 'lat' => 55.4833, 'lng' => 12.1833, 'stills' => 'Multiple', 'still_types' => 'Pot and column', 'expressions' => 'Braunstein Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, distilled, aged in oak.', 'website' => 'https://braunstein.dk/'],
        ['name' => 'Mosgaard Whisky', 'country' => 'Denmark', 'region' => 'Europe', 'lat' => 55.4, 'lng' => 10.3833, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Mosgaard Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak.', 'website' => 'https://mosgaardwhisky.dk/'],
        ['name' => 'Nordisk Brænderi', 'country' => 'Denmark', 'region' => 'Europe', 'lat' => 55.5, 'lng' => 9.75, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Nordisk Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak.', 'website' => 'https://nordiskbraenderi.dk/'],
        ['name' => 'Sugar Baron', 'country' => 'South Africa', 'region' => 'Africa', 'lat' => -29.5, 'lng' => 30.5, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Sugar Baron Agricole', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot distilled, aged in oak; Agricole style.', 'website' => 'https://sugarbaron.co.za/'],
        ['name' => 'Mhoba Rum', 'country' => 'South Africa', 'region' => 'Africa', 'lat' => -25.4833, 'lng' => 31.5167, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Mhoba Select Reserve, Pot Stilled High Ester', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented long with dunder, pot distilled, aged in oak.', 'website' => 'https://mhoba.com/'],
        ['name' => 'Tapanga Rum', 'country' => 'South Africa', 'region' => 'Africa', 'lat' => -29.8333, 'lng' => 31.0, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Tapanga Single Estate', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot distilled, aged in oak.', 'website' => 'https://tapangarum.com/'],
        ['name' => 'Cape of Storms Distilling Company', 'country' => 'South Africa', 'region' => 'Africa', 'lat' => -33.9333, 'lng' => 18.4667, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Cape of Storms Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented with Caribbean technique, pot distilled, aged in oak.', 'website' => 'https://capeofstormsdistillery.com/'],
        ['name' => 'Whistler Rum', 'country' => 'South Africa', 'region' => 'Africa', 'lat' => -29.8333, 'lng' => 31.0, 'stills' => 'Multiple', 'still_types' => 'Pot and column', 'expressions' => 'Whistler Dark, Spiced', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, distilled, aged in oak; largest in SA.', 'website' => 'https://whistlerrum.co.za/'],
        ['name' => 'Innocent Spirits Distillery', 'country' => 'South Africa', 'region' => 'Africa', 'lat' => -33.9167, 'lng' => 18.4167, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Innocent Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak.', 'website' => 'https://innocentspirits.com/'],
        ['name' => 'Incendo Distillery', 'country' => 'South Africa', 'region' => 'Africa', 'lat' => -25.7333, 'lng' => 27.8833, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Incendo Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak.', 'website' => 'https://incendo.co.za/'],
        ['name' => 'Brickmaker’s Distilling Co.', 'country' => 'South Africa', 'region' => 'Africa', 'lat' => -33.9667, 'lng' => 25.6, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Rhino Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, spiced.', 'website' => 'https://brickmakersdistillery.com/'],
        ['name' => 'De Vry Distillery', 'country' => 'South Africa', 'region' => 'Africa', 'lat' => -29.0, 'lng' => 26.0, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Die Warm Rasta Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, distilled, aged in charred barrels.', 'website' => 'https://devrydistillery.co.za/'],
        ['name' => 'Durbanville Distillery', 'country' => 'South Africa', 'region' => 'Africa', 'lat' => -33.8333, 'lng' => 18.65, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Durbanville Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled cold process, aged in oak.', 'website' => 'https://durbanvilledistillery.com/'],
        ['name' => 'Grays Distillery', 'country' => 'Mauritius', 'region' => 'Africa', 'lat' => -20.1, 'lng' => 57.5833, 'stills' => 'Multiple', 'still_types' => 'Pot and column stills', 'expressions' => 'New Grove, Lazy Dodo, Mauricia', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses/cane juice', 'production_process' => 'Molasses or cane juice fermented, pot/column distilled, aged in oak.', 'website' => 'https://newgrove.mu/'],
        ['name' => 'Rhumerie de Chamarel', 'country' => 'Mauritius', 'region' => 'Africa', 'lat' => -20.4167, 'lng' => 57.3833, 'stills' => 'Multiple', 'still_types' => 'Creole column stills', 'expressions' => 'Chamarel Blanc, Vieux, XO', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, Creole column distilled, aged in oak.', 'website' => 'https://rhumeriedechamarel.com/'],
        ['name' => 'Distillerie De Labourdonnais', 'country' => 'Mauritius', 'region' => 'Africa', 'lat' => -20.0667, 'lng' => 57.6167, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'La Bourdonnais Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, column distilled, aged in oak.', 'website' => 'https://labourdonnais.com/'],
        ['name' => 'St Aubin', 'country' => 'Mauritius', 'region' => 'Africa', 'lat' => -20.5, 'lng' => 57.55, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'St Aubin Blanc, Vieux', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, column distilled, aged in oak.', 'website' => 'https://staubin.mu/'],
        ['name' => 'Oxenham', 'country' => 'Mauritius', 'region' => 'Africa', 'lat' => -20.2833, 'lng' => 57.5, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Bouganville, Penny Blue', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'https://oxenham.mu/'],
        ['name' => 'Savanna', 'country' => 'Réunion', 'region' => 'Africa', 'lat' => -20.8833, 'lng' => 55.2833, 'stills' => 'Multiple', 'still_types' => 'Creole column and pot stills', 'expressions' => 'Savanna Blanc, Vieux, Grand Arôme', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses/cane juice', 'production_process' => 'Molasses or cane juice fermented long for esters, distilled, aged in oak.', 'website' => 'https://savanna.fr/'],
        ['name' => 'Isautier', 'country' => 'Réunion', 'region' => 'Africa', 'lat' => -21.3333, 'lng' => 55.4667, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Isautier Blanc, Arrangé', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses/cane juice', 'production_process' => 'Molasses or cane juice fermented, column distilled, some aged.', 'website' => 'https://isautier.com/'],
        ['name' => 'Rivière du Mât', 'country' => 'Réunion', 'region' => 'Africa', 'lat' => -21.0333, 'lng' => 55.7167, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Rivière du Mât Blanc, Opé', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'https://riviere-du-mat.com/'],
        ['name' => 'Groupe Vidzar (Dzama)', 'country' => 'Madagascar', 'region' => 'Africa', 'lat' => -13.3167, 'lng' => 48.2667, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Dzama Cuvée Noire, Vieux 6 Ans', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, column distilled, aged in oak.', 'website' => 'https://dzama.com/'],
        ['name' => 'Takamaka (Trois Frères)', 'country' => 'Seychelles', 'region' => 'Africa', 'lat' => -4.7333, 'lng' => 55.5167, 'stills' => 'Multiple', 'still_types' => 'Pot and column stills', 'expressions' => 'Takamaka Blanc, Dark Spiced, Overproof', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses/cane juice', 'production_process' => 'Molasses or cane juice fermented, distilled, aged in oak.', 'website' => 'https://takamakarum.com/'],
        ['name' => 'Barbosa Amado & Vicente', 'country' => 'Cape Verde', 'region' => 'Africa', 'lat' => 16.5333, 'lng' => -22.9167, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Barbosa Grogue', 'water_source' => 'Local', 'barrel_sources' => 'Not aged', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot distilled, unaged; Grogue style.', 'website' => 'Not specified'],
        ['name' => 'M&G (Musica e Grogue)', 'country' => 'Cape Verde', 'region' => 'Africa', 'lat' => 17.0, 'lng' => -25.1667, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'M&G Grogue Natural', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot distilled, some aged.', 'website' => 'Not specified'],
        ['name' => 'Sodade', 'country' => 'Cape Verde', 'region' => 'Africa', 'lat' => 15.0, 'lng' => -23.6167, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Sodade Grogue', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot distilled, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'MIM Distillery', 'country' => 'Ghana', 'region' => 'Africa', 'lat' => 6.0, 'lng' => -2.0, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'MIM Cashew Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot distilled, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'GIHOC Distilleries', 'country' => 'Ghana', 'region' => 'Africa', 'lat' => 5.55, 'lng' => -0.2, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'GIHOC Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'https://gihocdistil.com/'],
        ['name' => 'Reign Forest Distillery', 'country' => 'Ghana', 'region' => 'Africa', 'lat' => 5.6037, 'lng' => -0.187, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Reign Spiced Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, spiced and aged.', 'website' => 'Not specified'],
        ['name' => 'Bahari Rum', 'country' => 'Kenya', 'region' => 'Africa', 'lat' => -4.1667, 'lng' => 39.45, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Bahari 3 Years, 12 Years Single Cask', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak; blended with Mauritian rum.', 'website' => 'https://bahari-rum.com/'],
        ['name' => 'London Distillers Kenya', 'country' => 'Kenya', 'region' => 'Africa', 'lat' => -1.45, 'lng' => 36.9833, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Oak Cask Premium Dark Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'https://londondistillers.com/'],
        ['name' => 'Sangar Rum (Miseh Distilling)', 'country' => 'Liberia', 'region' => 'Africa', 'lat' => 7.5, 'lng' => -8.8333, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Sangar White, Gold', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot distilled, aged in oak.', 'website' => 'https://sangarrum.com/'],
        ['name' => 'Porte Farm & Distillery', 'country' => 'Liberia', 'region' => 'Africa', 'lat' => 6.4167, 'lng' => -10.5833, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Porte Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot distilled, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'Amrut Distilleries', 'country' => 'India', 'region' => 'Asia-Pacific', 'lat' => 12.9716, 'lng' => 77.5946, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Two Indies Rum, Two Indies White Rum, Bella Jaggery Rum', 'water_source' => 'Local', 'barrel_sources' => 'Ex-bourbon', 'raw_material' => 'Jaggery (unrefined cane sugar) and molasses', 'production_process' => 'Jaggery or molasses fermented, pot distilled, aged in ex-bourbon barrels; blends with Caribbean rums for some expressions.', 'website' => 'https://amrutdistilleries.com/'],
        ['name' => 'Piccadily Distilleries (Camikara)', 'country' => 'India', 'region' => 'Asia-Pacific', 'lat' => 29.8833, 'lng' => 77.0667, 'stills' => 'Multiple', 'still_types' => 'Pot and column stills', 'expressions' => 'Camikara 8 Year, 12 Year', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot/column distilled, aged in oak for 8-12 years.', 'website' => 'https://piccadily.com/'],
        ['name' => 'Mohan Meakin Ltd (Old Monk)', 'country' => 'India', 'region' => 'Asia-Pacific', 'lat' => 30.9, 'lng' => 77.05, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Old Monk Supreme, Legend, Gold Reserve', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak; historic process since 1855.', 'website' => 'https://mohanmeakin.com/'],
        ['name' => 'Radico Khaitan (Rampur)', 'country' => 'India', 'region' => 'Asia-Pacific', 'lat' => 28.8, 'lng' => 79.0333, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Rampur Select, Signature Reserve', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak.', 'website' => 'https://radico.co.in/'],
        ['name' => 'Himmaleh Spirits', 'country' => 'India', 'region' => 'Asia-Pacific', 'lat' => 29.2167, 'lng' => 78.95, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Neoli Himalayan Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak at high altitude.', 'website' => 'https://himmalehspirits.com/'],
        ['name' => 'Tanduay Distillers', 'country' => 'Philippines', 'region' => 'Asia-Pacific', 'lat' => 14.2783, 'lng' => 121.1247, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Tanduay Dark, 5 Year, 12 Year, Especial', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'https://www.tanduay.com/'],
        ['name' => 'Don Papa Rum (Bleeding Heart Rum Co.)', 'country' => 'Philippines', 'region' => 'Asia-Pacific', 'lat' => 10.5, 'lng' => 122.9, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Don Papa 7 Year, 10 Year, Rare Cask', 'water_source' => 'Local', 'barrel_sources' => 'Ex-bourbon', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in ex-bourbon barrels.', 'website' => 'https://donpaparum.com/'],
        ['name' => 'Destileria Limtuaco', 'country' => 'Philippines', 'region' => 'Asia-Pacific', 'lat' => 14.5833, 'lng' => 121.0, 'stills' => 'Multiple', 'still_types' => 'Pot and column stills', 'expressions' => 'Paradise Mango Rum, Old Captain Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, distilled, aged in oak; fruit infusions.', 'website' => 'https://www.limtuaco.com/'],
        ['name' => 'Don Tikyo Rum (COLSOL Distillery)', 'country' => 'Philippines', 'region' => 'Asia-Pacific', 'lat' => 10.9167, 'lng' => 121.9833, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Don Tikyo White, Gold', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot distilled, aged in oak.', 'website' => 'https://dontikyorum.com/'],
        ['name' => 'Luisita Rum (Tarlac Distillery Corp.)', 'country' => 'Philippines', 'region' => 'Asia-Pacific', 'lat' => 15.4667, 'lng' => 120.6, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Luisita Single Estate, Single Barrel', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'Chalong Bay Rum Distillery', 'country' => 'Thailand', 'region' => 'Asia-Pacific', 'lat' => 7.8416, 'lng' => 98.3524, 'stills' => 'Multiple', 'still_types' => 'Traditional copper still', 'expressions' => 'Identity, Tropical Notes Series, White Spiced', 'water_source' => 'Not specified', 'barrel_sources' => 'Not specified', 'raw_material' => 'Sugarcane juice', 'production_process' => 'Sugarcane hand-harvested, pressed for first-press juice, fermented, distilled in copper still, rested 8 months.', 'website' => 'https://chalongbayrum.com/'],
        ['name' => 'Issan Rum Distillery', 'country' => 'Thailand', 'region' => 'Asia-Pacific', 'lat' => 17.8833, 'lng' => 102.7333, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Issan White, Aged', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Organic cane juice fermented long with dunder, pot distilled, aged in oak.', 'website' => 'https://www.issanrum.com/'],
        ['name' => 'La Rhumerie De Koh Samui (Magic Alambic)', 'country' => 'Thailand', 'region' => 'Asia-Pacific', 'lat' => 9.5, 'lng' => 100.0, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Magic Alambic White, Spiced', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot distilled, aged in oak.', 'website' => 'Not specified'],
        ['name' => 'Sanpatong Distillery', 'country' => 'Thailand', 'region' => 'Asia-Pacific', 'lat' => 18.7833, 'lng' => 98.9833, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Sanpatong Rhum Agricole', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot distilled, aged in oak.', 'website' => 'https://www.sanpatong.com/'],
        ['name' => 'Helios Distillery (Teeda)', 'country' => 'Japan', 'region' => 'Asia-Pacific', 'lat' => 26.5833, 'lng' => 127.9833, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Teeda Blended, Kiyomi', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot distilled, aged in oak.', 'website' => 'https://helios-syuzo.co.jp/'],
        ['name' => 'Nine Leaves Distillery', 'country' => 'Japan', 'region' => 'Asia-Pacific', 'lat' => 35.0, 'lng' => 135.9167, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Nine Leaves Clear, Encrypted, Angel\'s Half', 'water_source' => 'Local spring (Lake Biwa)', 'barrel_sources' => 'Oak', 'raw_material' => 'Brown sugar', 'production_process' => 'Brown sugar fermented, pot distilled, aged in oak.', 'website' => 'https://www.nine-leaves.com/'],
        ['name' => 'Grace Rum Factory (Cor Cor)', 'country' => 'Japan', 'region' => 'Asia-Pacific', 'lat' => 26.5833, 'lng' => 127.9833, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Cor Cor Red, Green', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses/cane juice', 'production_process' => 'Molasses or cane juice fermented, pot distilled, aged in oak.', 'website' => 'https://grace-rum.com/'],
        ['name' => 'Kikusui Shuzo (Ryoma)', 'country' => 'Japan', 'region' => 'Asia-Pacific', 'lat' => 33.5667, 'lng' => 133.5333, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Ryoma Rhum Japonais', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented, pot distilled, aged in oak.', 'website' => 'https://kikusui-sake.com/'],
        ['name' => 'Spice Islands Distilling Co.', 'country' => 'Indonesia', 'region' => 'Asia-Pacific', 'lat' => -8.6833, 'lng' => 115.2667, 'stills' => 'Multiple', 'still_types' => 'Pot stills (550L)', 'expressions' => 'Spice Islands Rum', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, pot distilled, aged in oak with Indonesian spices.', 'website' => 'https://spiceislandsdistillingco.com/'],
        ['name' => 'Naga Rum', 'country' => 'Indonesia', 'region' => 'Asia-Pacific', 'lat' => -6.2088, 'lng' => 106.8456, 'stills' => 'Multiple', 'still_types' => 'Column stills', 'expressions' => 'Naga Triple Wood, Java Reserve', 'water_source' => 'Local', 'barrel_sources' => 'Teak/ex-bourbon/cherry', 'raw_material' => 'Molasses', 'production_process' => 'Molasses fermented, column distilled, aged in teak, ex-bourbon, cherry barrels.', 'website' => 'https://www.nagarum.com/'],
        ['name' => 'Distillerie d\'Indochine (Sampan)', 'country' => 'Vietnam', 'region' => 'Asia-Pacific', 'lat' => 15.8801, 'lng' => 108.338, 'stills' => 'Multiple', 'still_types' => 'French copper column still', 'expressions' => 'Sampan Blanc, Overproof, Vintage', 'water_source' => 'Local', 'barrel_sources' => 'Oak/ex-cognac', 'raw_material' => 'Cane juice', 'production_process' => 'Organic cane juice fermented, column distilled, aged in oak or ex-cognac.', 'website' => 'https://www.distillerie-indochine.com/'],
        ['name' => 'Sông Cái Distillery', 'country' => 'Vietnam', 'region' => 'Asia-Pacific', 'lat' => 21.0285, 'lng' => 105.8412, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Song Cai Rum variants', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice/grains/botanicals', 'production_process' => 'Cane juice or botanicals fermented, pot distilled, aged in oak; focus on Vietnamese terroir.', 'website' => 'https://www.songcaidistillery.com/'],
        ['name' => 'Rhum Belami', 'country' => 'Vietnam', 'region' => 'Asia-Pacific', 'lat' => 21.0285, 'lng' => 105.8412, 'stills' => 'Multiple', 'still_types' => 'Pot stills', 'expressions' => 'Premium Dark Rhum 55%', 'water_source' => 'Local', 'barrel_sources' => 'Oak', 'raw_material' => 'Cane juice', 'production_process' => 'Cane juice fermented with baker\'s yeast, pot distilled, infused with botanicals, aged in oak.', 'website' => 'https://rhumbelami.com/'],
    ];
}
